//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class SystemClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * Service information
     */
    getInfo(signal?: AbortSignal): Promise<ServiceInfoDto> {
        let url_ = this.baseUrl + "/system";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetInfo(_response);
        });
    }

    protected processGetInfo(response: Response): Promise<ServiceInfoDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ServiceInfoDto;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ServiceInfoDto>(null as any);
    }
}

export class HealthClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * Liveness probe
     */
    getHealth(signal?: AbortSignal): Promise<HealthDto> {
        let url_ = this.baseUrl + "/health";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetHealth(_response);
        });
    }

    protected processGetHealth(response: Response): Promise<HealthDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as HealthDto;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<HealthDto>(null as any);
    }
}

export class AuthClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * The account the ID token belongs to
     */
    me(signal?: AbortSignal): Promise<UserDto> {
        let url_ = this.baseUrl + "/api/v1/auth/me";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processMe(_response);
        });
    }

    protected processMe(response: Response): Promise<UserDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as UserDto;
            return result200;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserDto>(null as any);
    }

    /**
     * Change the signed-in account's password
     * @return Changed. Firebase revokes the account's refresh tokens, so a client should sign in again rather than trust the session it holds.
     */
    changePassword(body: ChangePasswordDto, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/auth/me/password";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            signal,
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processChangePassword(_response);
        });
    }

    protected processChangePassword(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 204) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("The new password is unusable, or the same as the current one.", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token, or the wrong current password.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class LibraryClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @param type (optional) The type of the library item.
     * @param status (optional) All four, including the two only the job runner sets — a filter reads data it does not write.
     * @param sourceMode (optional) The source mode of the library item.
     * @param search (optional) Case-insensitive, matched against the title, the source name and a novel's author.
     * @param page (optional) 
     * @param pageSize (optional) 
     */
    list(type?: Type | undefined, status?: Status | undefined, sourceMode?: SourceMode | undefined, search?: string | undefined, page?: number | undefined, pageSize?: number | undefined, signal?: AbortSignal): Promise<LibraryItemPageDto> {
        let url_ = this.baseUrl + "/api/v1/library?";
        if (type === null)
            throw new globalThis.Error("The parameter 'type' cannot be null.");
        else if (type !== undefined)
            url_ += "type=" + encodeURIComponent("" + type) + "&";
        if (status === null)
            throw new globalThis.Error("The parameter 'status' cannot be null.");
        else if (status !== undefined)
            url_ += "status=" + encodeURIComponent("" + status) + "&";
        if (sourceMode === null)
            throw new globalThis.Error("The parameter 'sourceMode' cannot be null.");
        else if (sourceMode !== undefined)
            url_ += "sourceMode=" + encodeURIComponent("" + sourceMode) + "&";
        if (search === null)
            throw new globalThis.Error("The parameter 'search' cannot be null.");
        else if (search !== undefined)
            url_ += "search=" + encodeURIComponent("" + search) + "&";
        if (page === null)
            throw new globalThis.Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&";
        if (pageSize === null)
            throw new globalThis.Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processList(_response);
        });
    }

    protected processList(response: Response): Promise<LibraryItemPageDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as LibraryItemPageDto;
            return result200;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LibraryItemPageDto>(null as any);
    }

    create(body: CreateLibraryItemDto, signal?: AbortSignal): Promise<LibraryItemDto> {
        let url_ = this.baseUrl + "/api/v1/library";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreate(_response);
        });
    }

    protected processCreate(response: Response): Promise<LibraryItemDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result201: any = null;
            result201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as LibraryItemDto;
            return result201;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("A crawler item without its URL or crawler, a manual one with a URL, or metadata on an item that has none writable.", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LibraryItemDto>(null as any);
    }

    get(id: string, signal?: AbortSignal): Promise<LibraryItemDto> {
        let url_ = this.baseUrl + "/api/v1/library/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGet(_response);
        });
    }

    protected processGet(response: Response): Promise<LibraryItemDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as LibraryItemDto;
            return result200;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("No item under that id.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LibraryItemDto>(null as any);
    }

    replace(id: string, body: UpdateLibraryItemDto, signal?: AbortSignal): Promise<LibraryItemDto> {
        let url_ = this.baseUrl + "/api/v1/library/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processReplace(_response);
        });
    }

    protected processReplace(response: Response): Promise<LibraryItemDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as LibraryItemDto;
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("The creation rules, plus a changed `type` or `sourceMode`, or a status only the job runner may set.", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("No item under that id.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LibraryItemDto>(null as any);
    }

    /**
     * @return Deleted, and every chapter, image or clip filed under it with it.
     */
    remove(id: string, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/library/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            signal,
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRemove(_response);
        });
    }

    protected processRemove(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 204) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("No item under that id.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    export(id: string, signal?: AbortSignal): Promise<LibraryPackageDto> {
        let url_ = this.baseUrl + "/api/v1/library/{id}/export";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processExport(_response);
        });
    }

    protected processExport(response: Response): Promise<LibraryPackageDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as LibraryPackageDto;
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Only a novel can be packaged", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("No item under that id.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LibraryPackageDto>(null as any);
    }

    /**
     * @param status (optional) All five, including the ones only discovery and the job runner set — a filter reads data it does not write.
     * @param language (optional) The language of a chapter. Null for an asset.
     * @param type (optional) The type of content.
     * @param search (optional) Case-insensitive, matched against a chapter's title or an asset's filename.
     * @param page (optional) 
     * @param pageSize (optional) 
     */
    listContents(id: string, status?: Status2 | undefined, language?: Language | undefined, type?: Type2 | undefined, search?: string | undefined, page?: number | undefined, pageSize?: number | undefined, signal?: AbortSignal): Promise<LibraryContentPageDto> {
        let url_ = this.baseUrl + "/api/v1/library/{id}/contents?";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (status === null)
            throw new globalThis.Error("The parameter 'status' cannot be null.");
        else if (status !== undefined)
            url_ += "status=" + encodeURIComponent("" + status) + "&";
        if (language === null)
            throw new globalThis.Error("The parameter 'language' cannot be null.");
        else if (language !== undefined)
            url_ += "language=" + encodeURIComponent("" + language) + "&";
        if (type === null)
            throw new globalThis.Error("The parameter 'type' cannot be null.");
        else if (type !== undefined)
            url_ += "type=" + encodeURIComponent("" + type) + "&";
        if (search === null)
            throw new globalThis.Error("The parameter 'search' cannot be null.");
        else if (search !== undefined)
            url_ += "search=" + encodeURIComponent("" + search) + "&";
        if (page === null)
            throw new globalThis.Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&";
        if (pageSize === null)
            throw new globalThis.Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processListContents(_response);
        });
    }

    protected processListContents(response: Response): Promise<LibraryContentPageDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as LibraryContentPageDto;
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("A `language` filter that has nothing to match on an image or video item.", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("No item under that id, or no content under that one.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LibraryContentPageDto>(null as any);
    }

    createContent(id: string, body: CreateLibraryContentDto, signal?: AbortSignal): Promise<LibraryContentDto> {
        let url_ = this.baseUrl + "/api/v1/library/{id}/contents";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateContent(_response);
        });
    }

    protected processCreateContent(response: Response): Promise<LibraryContentDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result201: any = null;
            result201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as LibraryContentDto;
            return result201;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("A content type the item does not hold, fields belonging to a type the row is not, or a chapter without a title or a language. A status only discovery or the job runner may set.", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("No item under that id.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LibraryContentDto>(null as any);
    }

    getContent(id: string, contentId: string, signal?: AbortSignal): Promise<LibraryContentDto> {
        let url_ = this.baseUrl + "/api/v1/library/{id}/contents/{contentId}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (contentId === undefined || contentId === null)
            throw new globalThis.Error("The parameter 'contentId' must be defined.");
        url_ = url_.replace("{contentId}", encodeURIComponent("" + contentId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetContent(_response);
        });
    }

    protected processGetContent(response: Response): Promise<LibraryContentDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as LibraryContentDto;
            return result200;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("No item under that id, or no content under that one.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LibraryContentDto>(null as any);
    }

    replaceContent(id: string, contentId: string, body: UpdateLibraryContentDto, signal?: AbortSignal): Promise<LibraryContentDto> {
        let url_ = this.baseUrl + "/api/v1/library/{id}/contents/{contentId}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (contentId === undefined || contentId === null)
            throw new globalThis.Error("The parameter 'contentId' must be defined.");
        url_ = url_.replace("{contentId}", encodeURIComponent("" + contentId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processReplaceContent(_response);
        });
    }

    protected processReplaceContent(response: Response): Promise<LibraryContentDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as LibraryContentDto;
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("A content type the item does not hold, fields belonging to a type the row is not, or a chapter without a title or a language. A status only discovery or the job runner may set. A changed `type` is refused too.", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("No item under that id, or no content under that one.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LibraryContentDto>(null as any);
    }

    /**
     * @return Deleted. The stored bytes are not — whoever uploaded them drops them.
     */
    removeContent(id: string, contentId: string, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/library/{id}/contents/{contentId}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (contentId === undefined || contentId === null)
            throw new globalThis.Error("The parameter 'contentId' must be defined.");
        url_ = url_.replace("{contentId}", encodeURIComponent("" + contentId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            signal,
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRemoveContent(_response);
        });
    }

    protected processRemoveContent(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 204) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("No item under that id, or no content under that one.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class ScrapingClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    preview(body: PreviewRequestDto, signal?: AbortSignal): Promise<PreviewDto> {
        let url_ = this.baseUrl + "/api/v1/scrapings/preview";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPreview(_response);
        });
    }

    protected processPreview(response: Response): Promise<PreviewDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as PreviewDto;
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("A URL that is not on the crawler\'s own site.", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("No crawler under that name, or no book at that URL.", status, _responseText, _headers);
            });
        } else if (status === 502) {
            return response.text().then((_responseText) => {
            return throwException("The source or the browser behind the scraping service failed.", status, _responseText, _headers);
            });
        } else if (status === 503) {
            return response.text().then((_responseText) => {
            return throwException("The scraping service did not answer, or did not answer in time.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PreviewDto>(null as any);
    }

    /**
     * @return Read, compared, appended. The counters are as they now stand.
     */
    discover(body: DiscoverDto, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/scrapings/discover";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDiscover(_response);
        });
    }

    protected processDiscover(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 202) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("A manual item \u2014 it has no source to read \u2014 or a `sourceUrl` that is not on the crawler\'s own site.", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("No item under that id, no crawler under its `sourceName`, or no book at its URL.", status, _responseText, _headers);
            });
        } else if (status === 501) {
            return response.text().then((_responseText) => {
            return throwException("A crawler item that is not a novel.", status, _responseText, _headers);
            });
        } else if (status === 502) {
            return response.text().then((_responseText) => {
            return throwException("The source or the browser behind the scraping service failed.", status, _responseText, _headers);
            });
        } else if (status === 503) {
            return response.text().then((_responseText) => {
            return throwException("The scraping service did not answer, or did not answer in time.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param state (optional) One of the screen's three tabs. Omitted lists every job.
     * @param libraryType (optional) The type of the item scraped, as it was when the job was described.
     * @param libraryId (optional) Every job over one item — what an item screen asks for.
     * @param page (optional) 
     * @param pageSize (optional) 
     * @return Newest first, each with the tasks it described.
     */
    listJobs(state?: State | undefined, libraryType?: LibraryType | undefined, libraryId?: string | undefined, page?: number | undefined, pageSize?: number | undefined, signal?: AbortSignal): Promise<ScrapingJobPageDto> {
        let url_ = this.baseUrl + "/api/v1/scrapings/scraping/jobs?";
        if (state === null)
            throw new globalThis.Error("The parameter 'state' cannot be null.");
        else if (state !== undefined)
            url_ += "state=" + encodeURIComponent("" + state) + "&";
        if (libraryType === null)
            throw new globalThis.Error("The parameter 'libraryType' cannot be null.");
        else if (libraryType !== undefined)
            url_ += "libraryType=" + encodeURIComponent("" + libraryType) + "&";
        if (libraryId === null)
            throw new globalThis.Error("The parameter 'libraryId' cannot be null.");
        else if (libraryId !== undefined)
            url_ += "libraryId=" + encodeURIComponent("" + libraryId) + "&";
        if (page === null)
            throw new globalThis.Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&";
        if (pageSize === null)
            throw new globalThis.Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processListJobs(_response);
        });
    }

    protected processListJobs(response: Response): Promise<ScrapingJobPageDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ScrapingJobPageDto;
            return result200;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ScrapingJobPageDto>(null as any);
    }

    /**
     * @return Persisted, and published or booked. A range that matched nothing is a `completed` record with `total: 0`.
     */
    createJob(body: CreateScrapingJobDto, signal?: AbortSignal): Promise<ScrapingJobDto> {
        let url_ = this.baseUrl + "/api/v1/scrapings/scraping/jobs";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateJob(_response);
        });
    }

    protected processCreateJob(response: Response): Promise<ScrapingJobDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result201: any = null;
            result201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ScrapingJobDto;
            return result201;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("A manual item, a range that will not parse, or a `startAt` that has passed.", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("No item under that id, or no crawler under its `sourceName`.", status, _responseText, _headers);
            });
        } else if (status === 501) {
            return response.text().then((_responseText) => {
            return throwException("A crawler item that is not a novel.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ScrapingJobDto>(null as any);
    }

    /**
     * @return Deleted, and every task filed under it with it.
     */
    deleteJob(id: string, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/scrapings/scraping/jobs/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            signal,
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDeleteJob(_response);
        });
    }

    protected processDeleteJob(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 204) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("A job that has not settled \u2014 cancel it first, then delete it.", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("No job under that id.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Written, published where the new status is `queued`, and mirrored.
     */
    updateJobStatus(id: string, body: UpdateScrapingJobStatusDto, signal?: AbortSignal): Promise<ScrapingJobDto> {
        let url_ = this.baseUrl + "/api/v1/scrapings/scraping/jobs/{id}/status";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateJobStatus(_response);
        });
    }

    protected processUpdateJobStatus(response: Response): Promise<ScrapingJobDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ScrapingJobDto;
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("A status this job cannot reach from where it stands \u2014 including anything at all asked of a settled job.", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("No job under that id.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ScrapingJobDto>(null as any);
    }
}

/** The environment that build was configured for, as recorded on boot. */
export type NodeEnv = "development" | "test" | "production";

export interface ServiceInfoDto {
    name: string;
    /** Version from the package manifest. */
    version: string;
    /** The environment that build was configured for, as recorded on boot. */
    environment: NodeEnv;
    /** The version its versioned endpoints answer on when a client names none. */
    apiVersion: string;
    /** The data shape this build expects to find in the database. */
    schemaVersion: number;
    /** When this service first started against this database. */
    installedAt: string;
    /** When the process now serving started, as recorded on boot. */
    lastStartedAt: string;
}

export type HealthStatus = "ok";

/** Whether Firestore answered a single read within the probe deadline. */
export type FirebaseStatus = "up" | "down";

export interface HealthDto {
    status: HealthStatus;
    /** Seconds since the process started. */
    uptimeSeconds: number;
    /** Whether Firestore answered a single read within the probe deadline. */
    firebaseStatus: FirebaseStatus;
}

export interface UserDto {
    /** The Firebase uid. */
    id: string;
    email: string;
    /** The account's display name, empty if it has none. */
    name: string;
    emailVerified: boolean;
    photoUrl: string | null;
    /** UTC, as Firebase reports it. */
    createdAt: string;
    /** Null until the account has signed in once. */
    lastSignInAt: string | null;
}

export interface ChangePasswordDto {
    /** The password in use, as proof it is the owner asking and not a stolen token. */
    currentPassword: string;
    newPassword: string;
}

/** Set on creation and immutable after it. */
export type LibrarySourceMode = "manual" | "crawler";

export interface NovelMetadataDto {
    /** Pieces the source is known to have. */
    discoveredCount: number;
    /** How many of them are stored here. */
    downloadedCount: number;
    /** When the source was last read for that inventory. */
    discoveredAt: string | null;
    /** The work's own status, as its source publishes it. */
    status: NovelMetadataDtoStatus;
    /** The author's name. */
    author: string;
    /** The language the work is written in. */
    language: string;
    /** The genres the work belongs to. */
    genres: string[];
    /** A brief summary of the work. */
    description: string;
}

export interface ImageSetMetadataDto {
    /** Pieces the source is known to have. */
    discoveredCount: number;
    /** How many of them are stored here. */
    downloadedCount: number;
    /** When the source was last read for that inventory. */
    discoveredAt: string | null;
    /** Bytes held. */
    downloadedSize: number;
}

export interface VideoSetMetadataDto {
    /** Pieces the source is known to have. */
    discoveredCount: number;
    /** How many of them are stored here. */
    downloadedCount: number;
    /** When the source was last read for that inventory. */
    discoveredAt: string | null;
    /** Bytes held. */
    downloadedSize: number;
    /** Seconds held. */
    downloadedDuration: number;
}

export interface LibraryItemDto {
    /** The unique identifier of the library item. */
    id: string;
    /** Set on creation and immutable after it. */
    type: LibraryItemDtoType;
    /** The title of the library item. */
    title: string;
    /** Where the item is in our pipeline. */
    status: LibraryItemDtoStatus;
    /** Set on creation and immutable after it. */
    sourceMode: LibrarySourceMode;
    /** `Manual`, or the crawler's name. */
    sourceName: string;
    /** What a crawler reads. Null for a manual item. */
    sourceUrl?: string | null;
    /** A cover image URL, or null where the listing draws its placeholder. */
    coverUrl?: string | null;
    /** Metadata specific to novels. */
    novelMetadata?: NovelMetadata | null;
    /** Metadata specific to image sets. */
    imageMetadata?: ImageMetadata | null;
    /** Metadata specific to video sets. */
    videoMetadata?: VideoMetadata | null;
    /** Set on creation. */
    createdAt: string;
    /** Rewritten on every write. The listing is ordered by it. */
    updatedAt: string;
}

export interface LibraryItemPageDto {
    /** This page, ordered by `updatedAt` descending. */
    items: LibraryItemDto[];
    /** What matches the filter, not what this page holds. */
    total: number;
    /** The current page number. */
    page: number;
    /** The number of items per page. */
    pageSize: number;
}

export interface CreateLibraryItemDto {
    /** Immutable after creation — it decides the shape of `metadata`. */
    type: CreateLibraryItemDtoType;
    /** The title of the library item. */
    title: string;
    /** The status of the library item. */
    status: CreateLibraryItemDtoStatus;
    /** Immutable after creation — it decides how content arrives. */
    sourceMode: CreateLibraryItemDtoSourceMode;
    /** Which crawler, for a crawler item — required of one. A manual item is `Manual`, whatever is sent. */
    sourceName?: string;
    /** What the crawler reads. Required of a crawler item, and refused of a manual one. */
    sourceUrl?: any;
    /** A link to a cover image. Null, or left out, for the placeholder. */
    coverUrl?: any;
    /** The novel metadata of the library item, shape depends on the `type`. */
    novelMetadata?: any;
    /** The image metadata of the library item, shape depends on the `type`. */
    imageMetadata?: any;
    /** The video metadata of the library item, shape depends on the `type`. */
    videoMetadata?: any;
}

export interface UpdateLibraryItemDto {
    /** Immutable after creation — it decides the shape of `metadata`. */
    type: UpdateLibraryItemDtoType;
    /** The title of the library item. */
    title: string;
    /** The status of the library item. */
    status: UpdateLibraryItemDtoStatus;
    /** Immutable after creation — it decides how content arrives. */
    sourceMode: UpdateLibraryItemDtoSourceMode;
    /** Which crawler, for a crawler item — required of one. A manual item is `Manual`, whatever is sent. */
    sourceName?: string;
    /** What the crawler reads. Required of a crawler item, and refused of a manual one. */
    sourceUrl?: any;
    /** A link to a cover image. Null, or left out, for the placeholder. */
    coverUrl?: any;
    /** The novel metadata of the library item, shape depends on the `type`. */
    novelMetadata?: any;
    /** The image metadata of the library item, shape depends on the `type`. */
    imageMetadata?: any;
    /** The video metadata of the library item, shape depends on the `type`. */
    videoMetadata?: any;
}

export interface LibraryPackageDto {
    /** Where the archive is. Tokenised, and ready to open. */
    url: string;
    /** What the browser saves it as. */
    filename: string;
    /** What the archive weighs. */
    bytes: number;
    /** Text rows written — original chapters and translations together. */
    contents: number;
    /** Of those, how many had text to pack. The rest are discovered chapters nobody has scraped. */
    bodies: number;
    /** Translated rows per language, zeroes included. */
    translations: { [key: string]: number; };
}

export interface TextContentDto {
    /** The URL of the text content. */
    contentUrl: string | null;
    /** The language of the text content. */
    language: TextContentDtoLanguage;
    /** The title of the text content. */
    title: string;
    /** How long the stored text runs. Zero until there is text. */
    words: number;
}

export interface AudioContentDto {
    /** The URL of the audio content. */
    contentUrl: string | null;
    /** The language of the audio content. */
    language: AudioContentDtoLanguage;
    /** The URL of the subtitle content. */
    subtitleUrl: string | null;
}

export interface ImageContentDto {
    /** The URL of the image content. */
    contentUrl: string | null;
    /** The filename of the image content. */
    filename: string;
    /** The size of the image content in bytes. */
    filesize: number;
    /** The dimensions of the image content. */
    dimensions: string;
}

export interface VideoContentDto {
    /** The URL of the video content. */
    contentUrl: string | null;
    /** The filename of the video content. */
    filename: string;
    /** The size of the video content in bytes. */
    filesize: number;
    /** The dimensions of the video content. */
    dimensions: string;
    /** The duration of the video content in seconds. */
    duration: number;
}

export interface LibraryContentDto {
    /** The unique identifier of the library content. */
    id: string;
    /** The chapter number, and what the list is ordered by. */
    idx: number;
    /** The item's own type. Set from the parent, never sent. */
    type: LibraryContentDtoType;
    /** A life cycle. `pending` and `completed` follow from `contentUrl`; the other three are discovery's and the job runner's. */
    status: LibraryContentDtoStatus;
    /** Where the piece came from. Null for a row added by hand. */
    sourceUrl: string | null;
    /** The text content of the library item. */
    textContent?: TextContent | null;
    /** The audio content of the library item. */
    audioContent?: AudioContent | null;
    /** The image content of the library item. */
    imageContent?: ImageContent | null;
    /** The video content of the library item. */
    videoContent?: VideoContent | null;
    createdAt: string;
    updatedAt: string;
}

export interface LibraryContentPageDto {
    /** Chapters by their number, assets by their name. */
    items: LibraryContentDto[];
    /** What matches the filter, not what this page holds. */
    total: number;
    /** The current page number. */
    page: number;
    /** The number of items per page. */
    pageSize: number;
}

export interface CreateLibraryContentDto {
    /** A chapter only. Defaults to the next number up. */
    idx: number;
    /** The type of the content. */
    type: CreateLibraryContentDtoType;
    /** The status of the content. */
    status: CreateLibraryContentDtoStatus;
    /** Where the piece came from. Left out for a row added by hand. */
    sourceUrl?: any;
    /** The text content of the library item, shape depends on the `type`. */
    textContent?: TextContentDto;
    /** The audio content of the library item, shape depends on the `type`. */
    audioContent?: AudioContentDto;
    /** The image content of the library item, shape depends on the `type`. */
    imageContent?: ImageContentDto;
    /** The video content of the library item, shape depends on the `type`. */
    videoContent?: VideoContentDto;
}

export interface UpdateLibraryContentDto {
    /** A chapter only. Defaults to the next number up. */
    idx: number;
    /** The type of the content. */
    type: UpdateLibraryContentDtoType;
    /** The status of the content. */
    status: UpdateLibraryContentDtoStatus;
    /** Where the piece came from. Left out for a row added by hand. */
    sourceUrl?: any;
    /** The text content of the library item, shape depends on the `type`. */
    textContent?: TextContentDto;
    /** The audio content of the library item, shape depends on the `type`. */
    audioContent?: AudioContentDto;
    /** The image content of the library item, shape depends on the `type`. */
    imageContent?: ImageContentDto;
    /** The video content of the library item, shape depends on the `type`. */
    videoContent?: VideoContentDto;
}

export interface PreviewRequestDto {
    /** One of the registered crawlers. A name that is not registered is a 404. */
    crawler: string;
    /** The book's URL on the source site. A URL on another site is a 400. */
    sourceUrl: string;
    /** Skip the cached answer and read the source again. */
    refresh?: boolean;
}

/** The crawler's kind, which decides the shape of `content`. */
export type LibraryItemType = "novel" | "image" | "video";

/** The work's own status, mapped from the source's word for it. */
export type NovelStatus = "ongoing" | "complete" | "hiatus";

export interface NovelPreviewMetadataDto {
    /** The canonical book URL, so two spellings of one book normalise to one. */
    sourceUrl: string;
    title: string;
    author: string;
    /** The work's own status, mapped from the source's word for it. */
    status: NovelStatus;
    /** From the crawler's entry — the source does not publish one. */
    language: string;
    /** The source category, where it has one. */
    genres: string[];
    description: string;
    /** How many chapters the source has, or how many it says it has. */
    chapters: number;
    /** The newest chapter, as the source names it. */
    latest: string;
    latestUrl: string;
    /** When the source last changed, in the source's own format. Not an ISO instant, and not compared to one. */
    updatedAt: string;
    /** Where the cover lives on the source. Behind the same protection as the site, so not for an `<img>` — use `coverBinary`. */
    coverUrl: string | null;
}

export interface NovelPreviewDto {
    metadata: NovelPreviewMetadataDto;
    /** The cover as a data URI — the bytes and their type in one string. Null where the book has no cover, or fetching it failed. */
    coverBinary: string | null;
}

export interface PreviewDto {
    /** The crawler's kind, which decides the shape of `content`. */
    type: LibraryItemType;
    novelContent: NovelPreviewDto;
}

export interface DiscoverDto {
    /** The crawler item to read the source of. A manual item is a 400. */
    libraryId: string;
}

export interface ScrapingTaskDto {
    /** The library content row this task is for — and this task's own id. */
    id: string;
    /** The library content row this task is for. */
    contentId: string;
    /** Denormalised so a task reads on its own. */
    libraryId: string;
    /** The chapter number — what the list is ordered by. */
    index: number;
    /** The URL where the content can be fetched from. */
    sourceUrl: string;
    /** The task status. */
    status: ScrapingTaskDtoStatus;
    /** The job's, copied down: it is what the message carries. */
    refetch: boolean;
    /** The job's, copied down, for the same reason. */
    retry: number;
    /** When a consumer picked this task up. */
    startAt: string | null;
    /** When the task was completed. */
    completedAt: string | null;
    /** The last failure, in one line. */
    error: string | null;
    /** When the task was created. */
    createdAt: string;
    /** When the task was last updated. */
    updatedAt: string;
}

export interface ScrapingJobDto {
    /** The unique identifier of the scraping job. */
    id: string;
    /** The library this scraping job belongs to. */
    libraryId: string;
    /** The item's type, as it was. What the listing's library filter narrows on. */
    libraryType: ScrapingJobDtoLibraryType;
    /** As the item was called when the job was described. */
    libraryTitle: string;
    /** The item's `sourceName`, carried so a republish needs no read of it. */
    crawler: string;
    /** The task status. */
    status: ScrapingJobDtoStatus;
    /** The expression as it was sent. Drawn verbatim in the panel. */
    range: string;
    /** Whether a chapter that already holds text is fetched again. */
    refetch: boolean;
    /** How many times a failed task is tried again. */
    retry: number;
    /** When the job is due. Null was queued immediately. */
    startAt: string | null;
    /** When its messages actually went out. */
    queuedAt: string | null;
    /** When it settled, whichever way. */
    completedAt: string | null;
    /** Tasks in the job. What the progress bar divides by. */
    total: number;
    /** How many tasks have been completed. */
    completed: number;
    /** How many tasks have failed. */
    failed: number;
    /** Candidates dropped as already complete. */
    skipped: number;
    /** When the task was created. */
    createdAt: string;
    /** When the task was last updated. */
    updatedAt: string;
    /** One per piece of content in range, by its number. */
    tasks: ScrapingTaskDto[];
}

export interface ScrapingJobPageDto {
    /** Newest first, each with the tasks it described. */
    items: ScrapingJobDto[];
    /** What matches the filter, not what this page holds. */
    total: number;
    /** The current page number. */
    page: number;
    /** The number of items per page. */
    pageSize: number;
}

export interface CreateScrapingJobDto {
    /** The crawler item to scrape. A manual item is a 400. */
    libraryId: string;
    /** `all`, `missing`, or an index expression — `1,3,5,7`, `23-34`, `[23:34]`. Anything else is a 400. */
    range: string;
    /** Whether a chapter that already holds text is fetched again. */
    refetch?: boolean;
    /** When to publish the work. Null queues it now. */
    startAt?: any;
    /** How many times a failed chapter is tried again. The dialog offers 3, 1 and 0. */
    retry?: number;
}

export interface UpdateScrapingJobStatusDto {
    /** Where to take the job. A status it cannot reach from where it stands is a 400. */
    status: UpdateScrapingJobStatusDtoStatus;
}

export type Type = "novel" | "image" | "video";

export type Status = "draft" | "scraping" | "ready" | "failed";

export type SourceMode = "manual" | "crawler";

export type Status2 = "discovered" | "pending" | "inprogress" | "completed" | "failed";

export type Language = "vi" | "en" | "zh";

export type Type2 = "original" | "translation" | "audio" | "image" | "video";

export type State = "active" | "scheduled" | "history";

export type LibraryType = "novel" | "image" | "video";

export type NovelMetadataDtoStatus = "ongoing" | "complete" | "hiatus";

export type LibraryItemDtoType = "novel" | "image" | "video";

export type LibraryItemDtoStatus = "draft" | "scraping" | "ready" | "failed";

export interface NovelMetadata extends NovelMetadataDto {

    [key: string]: any;
}

export interface ImageMetadata extends ImageSetMetadataDto {

    [key: string]: any;
}

export interface VideoMetadata extends VideoSetMetadataDto {

    [key: string]: any;
}

export type CreateLibraryItemDtoType = "novel" | "image" | "video";

export type CreateLibraryItemDtoStatus = "draft" | "scraping" | "ready" | "failed";

export type CreateLibraryItemDtoSourceMode = "manual" | "crawler";

export type UpdateLibraryItemDtoType = "novel" | "image" | "video";

export type UpdateLibraryItemDtoStatus = "draft" | "scraping" | "ready" | "failed";

export type UpdateLibraryItemDtoSourceMode = "manual" | "crawler";

export type TextContentDtoLanguage = "vi" | "en" | "zh";

export type AudioContentDtoLanguage = "vi" | "en" | "zh";

export type LibraryContentDtoType = "original" | "translation" | "audio" | "image" | "video";

export type LibraryContentDtoStatus = "discovered" | "pending" | "inprogress" | "completed" | "failed";

export interface TextContent extends TextContentDto {

    [key: string]: any;
}

export interface AudioContent extends AudioContentDto {

    [key: string]: any;
}

export interface ImageContent extends ImageContentDto {

    [key: string]: any;
}

export interface VideoContent extends VideoContentDto {

    [key: string]: any;
}

export type CreateLibraryContentDtoType = "original" | "translation" | "audio" | "image" | "video";

export type CreateLibraryContentDtoStatus = "discovered" | "pending" | "inprogress" | "completed" | "failed";

export type UpdateLibraryContentDtoType = "original" | "translation" | "audio" | "image" | "video";

export type UpdateLibraryContentDtoStatus = "discovered" | "pending" | "inprogress" | "completed" | "failed";

export type ScrapingTaskDtoStatus = "scheduled" | "queued" | "running" | "paused" | "stopped" | "completed" | "failed";

export type ScrapingJobDtoLibraryType = "novel" | "image" | "video";

export type ScrapingJobDtoStatus = "scheduled" | "queued" | "running" | "paused" | "stopped" | "completed" | "failed";

export type UpdateScrapingJobStatusDtoStatus = "queued" | "paused" | "stopped";

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    throw new ApiException(message, status, response, headers, result);
}