//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class SystemClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * Service information
     */
    getInfo(signal?: AbortSignal): Promise<ServiceInfoDto> {
        let url_ = this.baseUrl + "/system";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetInfo(_response);
        });
    }

    protected processGetInfo(response: Response): Promise<ServiceInfoDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ServiceInfoDto;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ServiceInfoDto>(null as any);
    }
}

export class HealthClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * Liveness probe
     */
    getHealth(signal?: AbortSignal): Promise<HealthDto> {
        let url_ = this.baseUrl + "/health";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetHealth(_response);
        });
    }

    protected processGetHealth(response: Response): Promise<HealthDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as HealthDto;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<HealthDto>(null as any);
    }
}

export class AuthClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * The account the ID token belongs to
     */
    me(signal?: AbortSignal): Promise<UserDto> {
        let url_ = this.baseUrl + "/api/v1/auth/me";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processMe(_response);
        });
    }

    protected processMe(response: Response): Promise<UserDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as UserDto;
            return result200;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserDto>(null as any);
    }

    /**
     * Change the signed-in account's password
     * @return Changed. Firebase revokes the account's refresh tokens, so a client should sign in again rather than trust the session it holds.
     */
    changePassword(body: ChangePasswordDto, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/auth/me/password";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            signal,
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processChangePassword(_response);
        });
    }

    protected processChangePassword(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 204) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("The new password is unusable, or the same as the current one.", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token, or the wrong current password.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class LibraryClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * The items matching a filter, most recently changed first
     * @param type (optional) 
     * @param status (optional) All four, including the two only the job runner sets — a filter reads data it does not write.
     * @param sourceMode (optional) 
     * @param search (optional) Case-insensitive, matched against the title, the source name and a novel's author.
     * @param page (optional) 
     * @param pageSize (optional) 
     */
    list(type?: LibraryItemType | undefined, status?: LibraryItemStatus | undefined, sourceMode?: LibrarySourceMode | undefined, search?: string | undefined, page?: number | undefined, pageSize?: number | undefined, signal?: AbortSignal): Promise<LibraryItemPageDto> {
        let url_ = this.baseUrl + "/api/v1/library?";
        if (type === null)
            throw new globalThis.Error("The parameter 'type' cannot be null.");
        else if (type !== undefined)
            url_ += "type=" + encodeURIComponent("" + type) + "&";
        if (status === null)
            throw new globalThis.Error("The parameter 'status' cannot be null.");
        else if (status !== undefined)
            url_ += "status=" + encodeURIComponent("" + status) + "&";
        if (sourceMode === null)
            throw new globalThis.Error("The parameter 'sourceMode' cannot be null.");
        else if (sourceMode !== undefined)
            url_ += "sourceMode=" + encodeURIComponent("" + sourceMode) + "&";
        if (search === null)
            throw new globalThis.Error("The parameter 'search' cannot be null.");
        else if (search !== undefined)
            url_ += "search=" + encodeURIComponent("" + search) + "&";
        if (page === null)
            throw new globalThis.Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&";
        if (pageSize === null)
            throw new globalThis.Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processList(_response);
        });
    }

    protected processList(response: Response): Promise<LibraryItemPageDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as LibraryItemPageDto;
            return result200;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LibraryItemPageDto>(null as any);
    }

    /**
     * Add an item
     */
    create(body: CreateLibraryItemDto, signal?: AbortSignal): Promise<LibraryItemDto> {
        let url_ = this.baseUrl + "/api/v1/library";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreate(_response);
        });
    }

    protected processCreate(response: Response): Promise<LibraryItemDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result201: any = null;
            result201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as LibraryItemDto;
            return result201;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("A crawler item without its URL or crawler, a manual one with a URL, or metadata on an item that has none writable.", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LibraryItemDto>(null as any);
    }

    /**
     * One item
     */
    get(id: string, signal?: AbortSignal): Promise<LibraryItemDto> {
        let url_ = this.baseUrl + "/api/v1/library/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGet(_response);
        });
    }

    protected processGet(response: Response): Promise<LibraryItemDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as LibraryItemDto;
            return result200;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("No item under that id.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LibraryItemDto>(null as any);
    }

    /**
     * Replace an item's whole writable representation
     */
    replace(id: string, body: UpdateLibraryItemDto, signal?: AbortSignal): Promise<LibraryItemDto> {
        let url_ = this.baseUrl + "/api/v1/library/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processReplace(_response);
        });
    }

    protected processReplace(response: Response): Promise<LibraryItemDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as LibraryItemDto;
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("The creation rules, plus a changed `type` or `sourceMode`, or a status only the job runner may set.", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("No item under that id.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LibraryItemDto>(null as any);
    }

    /**
     * Delete an item
     * @return Deleted, and every chapter, image or clip filed under it with it.
     */
    remove(id: string, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/library/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            signal,
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRemove(_response);
        });
    }

    protected processRemove(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 204) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("No item under that id.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * One item's content — chapters by their number, assets by their name
     * @param status (optional) All three, including the one only the job runner sets — a filter reads data it does not write.
     * @param search (optional) Case-insensitive, matched against a chapter's title or an asset's filename.
     * @param page (optional) 
     * @param pageSize (optional) 
     */
    listContents(itemId: string, status?: LibraryContentStatus | undefined, search?: string | undefined, page?: number | undefined, pageSize?: number | undefined, signal?: AbortSignal): Promise<LibraryContentPageDto> {
        let url_ = this.baseUrl + "/api/v1/library/{itemId}/contents?";
        if (itemId === undefined || itemId === null)
            throw new globalThis.Error("The parameter 'itemId' must be defined.");
        url_ = url_.replace("{itemId}", encodeURIComponent("" + itemId));
        if (status === null)
            throw new globalThis.Error("The parameter 'status' cannot be null.");
        else if (status !== undefined)
            url_ += "status=" + encodeURIComponent("" + status) + "&";
        if (search === null)
            throw new globalThis.Error("The parameter 'search' cannot be null.");
        else if (search !== undefined)
            url_ += "search=" + encodeURIComponent("" + search) + "&";
        if (page === null)
            throw new globalThis.Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&";
        if (pageSize === null)
            throw new globalThis.Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processListContents(_response);
        });
    }

    protected processListContents(response: Response): Promise<LibraryContentPageDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as LibraryContentPageDto;
            return result200;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("No item under that id, or no content under that one.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LibraryContentPageDto>(null as any);
    }

    /**
     * Add a chapter, image or clip
     */
    createContent(itemId: string, body: CreateLibraryContentDto, signal?: AbortSignal): Promise<NovelChapterDto> {
        let url_ = this.baseUrl + "/api/v1/library/{itemId}/contents";
        if (itemId === undefined || itemId === null)
            throw new globalThis.Error("The parameter 'itemId' must be defined.");
        url_ = url_.replace("{itemId}", encodeURIComponent("" + itemId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateContent(_response);
        });
    }

    protected processCreateContent(response: Response): Promise<NovelChapterDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result201: any = null;
            result201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as NovelChapterDto;
            return result201;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Fields belonging to a type the item is not \u2014 a filename on a chapter, an index on an asset \u2014 or a chapter without a title.", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("No item under that id, or no content under that one.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<NovelChapterDto>(null as any);
    }

    /**
     * One chapter, image or clip
     */
    getContent(itemId: string, contentId: string, signal?: AbortSignal): Promise<NovelChapterDto> {
        let url_ = this.baseUrl + "/api/v1/library/{itemId}/contents/{contentId}";
        if (itemId === undefined || itemId === null)
            throw new globalThis.Error("The parameter 'itemId' must be defined.");
        url_ = url_.replace("{itemId}", encodeURIComponent("" + itemId));
        if (contentId === undefined || contentId === null)
            throw new globalThis.Error("The parameter 'contentId' must be defined.");
        url_ = url_.replace("{contentId}", encodeURIComponent("" + contentId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetContent(_response);
        });
    }

    protected processGetContent(response: Response): Promise<NovelChapterDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as NovelChapterDto;
            return result200;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("No item under that id, or no content under that one.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<NovelChapterDto>(null as any);
    }

    /**
     * Replace a row's whole writable representation
     */
    replaceContent(itemId: string, contentId: string, body: UpdateLibraryContentDto, signal?: AbortSignal): Promise<NovelChapterDto> {
        let url_ = this.baseUrl + "/api/v1/library/{itemId}/contents/{contentId}";
        if (itemId === undefined || itemId === null)
            throw new globalThis.Error("The parameter 'itemId' must be defined.");
        url_ = url_.replace("{itemId}", encodeURIComponent("" + itemId));
        if (contentId === undefined || contentId === null)
            throw new globalThis.Error("The parameter 'contentId' must be defined.");
        url_ = url_.replace("{contentId}", encodeURIComponent("" + contentId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processReplaceContent(_response);
        });
    }

    protected processReplaceContent(response: Response): Promise<NovelChapterDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as NovelChapterDto;
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Fields belonging to a type the item is not \u2014 a filename on a chapter, an index on an asset \u2014 or a chapter without a title.", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("No item under that id, or no content under that one.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<NovelChapterDto>(null as any);
    }

    /**
     * Delete a chapter, image or clip
     * @return Deleted. The stored bytes are not — whoever uploaded them drops them.
     */
    removeContent(itemId: string, contentId: string, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/v1/library/{itemId}/contents/{contentId}";
        if (itemId === undefined || itemId === null)
            throw new globalThis.Error("The parameter 'itemId' must be defined.");
        url_ = url_.replace("{itemId}", encodeURIComponent("" + itemId));
        if (contentId === undefined || contentId === null)
            throw new globalThis.Error("The parameter 'contentId' must be defined.");
        url_ = url_.replace("{contentId}", encodeURIComponent("" + contentId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            signal,
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRemoveContent(_response);
        });
    }

    protected processRemoveContent(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 204) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("No item under that id, or no content under that one.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class ScrapingClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * Read a source, and answer with what the preview screen draws
     * @param refresh (optional) Skip the cached answer and read the source again.
     */
    validate(body: ValidateDto, refresh?: boolean | undefined, signal?: AbortSignal): Promise<PreviewDto> {
        let url_ = this.baseUrl + "/api/v1/scraping/validate?";
        if (refresh === null)
            throw new globalThis.Error("The parameter 'refresh' cannot be null.");
        else if (refresh !== undefined)
            url_ += "refresh=" + encodeURIComponent("" + refresh) + "&";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processValidate(_response);
        });
    }

    protected processValidate(response: Response): Promise<PreviewDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as PreviewDto;
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("A URL that is not on the crawler\'s own site.", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Missing or invalid ID token.", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("No crawler under that name, or no book at that URL.", status, _responseText, _headers);
            });
        } else if (status === 502) {
            return response.text().then((_responseText) => {
            return throwException("The source or the browser behind the scraping service failed.", status, _responseText, _headers);
            });
        } else if (status === 503) {
            return response.text().then((_responseText) => {
            return throwException("The scraping service did not answer, or did not answer in time.", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PreviewDto>(null as any);
    }
}

/** The environment that build was configured for, as recorded on boot. */
export type NodeEnv = "development" | "test" | "production";

export interface ServiceInfoDto {
    name: string;
    /** Version from the package manifest. */
    version: string;
    /** The environment that build was configured for, as recorded on boot. */
    environment: NodeEnv;
    /** The version its versioned endpoints answer on when a client names none. */
    apiVersion: string;
    /** The data shape this build expects to find in the database. */
    schemaVersion: number;
    /** When this service first started against this database. */
    installedAt: string;
    /** When the process now serving started, as recorded on boot. */
    lastStartedAt: string;
}

export type HealthStatus = "ok";

/** Whether Firestore answered a single read within the probe deadline. */
export type FirebaseStatus = "up" | "down";

export interface HealthDto {
    status: HealthStatus;
    /** Seconds since the process started. */
    uptimeSeconds: number;
    /** Whether Firestore answered a single read within the probe deadline. */
    firebaseStatus: FirebaseStatus;
}

export interface UserDto {
    /** The Firebase uid. */
    id: string;
    email: string;
    /** The account's display name, empty if it has none. */
    name: string;
    emailVerified: boolean;
    photoUrl: string | null;
    /** UTC, as Firebase reports it. */
    createdAt: string;
    /** Null until the account has signed in once. */
    lastSignInAt: string | null;
}

export interface ChangePasswordDto {
    /** The password in use, as proof it is the owner asking and not a stolen token. */
    currentPassword: string;
    newPassword: string;
}

/** The item's own type. Set from the parent, never sent. */
export type NovelChapterType = "novel";

/** Derived from `contentUrl`. `failed` is the job runner's. */
export type LibraryContentStatus = "pending" | "ready" | "failed";

export interface NovelChapterDto {
    id: string;
    /** The item's own type. Set from the parent, never sent. */
    type: NovelChapterType;
    /** Where the bytes are. Null while the row is a placeholder. */
    contentUrl: string | null;
    /** Derived from `contentUrl`. `failed` is the job runner's. */
    status: LibraryContentStatus;
    createdAt: string;
    updatedAt: string;
    /** The chapter number, and what the list is ordered by. */
    index: number;
    title: string;
    language: string;
    /** How long the stored text runs. Zero until there is text. */
    words: number;
}

/** The item's own type. Set from the parent, never sent. */
export type ImageAssetType = "image";

export interface ImageAssetDto {
    id: string;
    /** The item's own type. Set from the parent, never sent. */
    type: ImageAssetType;
    /** Where the bytes are. Null while the row is a placeholder. */
    contentUrl: string | null;
    /** Derived from `contentUrl`. `failed` is the job runner's. */
    status: LibraryContentStatus;
    createdAt: string;
    updatedAt: string;
    filename: string;
    /** Bytes. */
    filesize: number;
}

/** The item's own type. Set from the parent, never sent. */
export type VideoAssetType = "video";

export interface VideoAssetDto {
    id: string;
    /** The item's own type. Set from the parent, never sent. */
    type: VideoAssetType;
    /** Where the bytes are. Null while the row is a placeholder. */
    contentUrl: string | null;
    /** Derived from `contentUrl`. `failed` is the job runner's. */
    status: LibraryContentStatus;
    createdAt: string;
    updatedAt: string;
    filename: string;
    /** Bytes. */
    filesize: number;
}

export type LibraryItemType = "novel" | "image" | "video";

export type LibraryItemStatus = "draft" | "scraping" | "ready" | "failed";

export type LibrarySourceMode = "manual" | "crawler";

/** The work's own status, as its source publishes it. */
export type NovelStatus = "ongoing" | "complete" | "hiatus";

export interface NovelMetadataDto {
    /** Pieces the source is known to have. */
    discoveredCount: number;
    /** When the source was last read for that inventory. */
    discoveredAt: string | null;
    /** How many of them are stored here. */
    downloadedCount: number;
    /** The work's own status, as its source publishes it. */
    status: NovelStatus;
    author: string;
    language: string;
    genres: string[];
    description: string;
}

export interface ImageSetMetadataDto {
    /** Pieces the source is known to have. */
    discoveredCount: number;
    /** When the source was last read for that inventory. */
    discoveredAt: string | null;
    /** How many of them are stored here. */
    downloadedCount: number;
    /** Bytes held. */
    downloadedSize: number;
}

export interface VideoSetMetadataDto {
    /** Pieces the source is known to have. */
    discoveredCount: number;
    /** When the source was last read for that inventory. */
    discoveredAt: string | null;
    /** How many of them are stored here. */
    downloadedCount: number;
    /** Bytes held. */
    downloadedSize: number;
    /** Seconds held. */
    downloadedDuration: number;
}

export interface LibraryListItemDto {
    id: string;
    /** Set on creation and immutable after it. */
    type: LibraryItemType;
    title: string;
    /** A cover image URL, or null where the listing draws its placeholder. */
    coverUrl: string | null;
    /** Set on creation and immutable after it. */
    sourceMode: LibrarySourceMode;
    /** `Manual`, or the crawler's name. */
    sourceName: string;
    /** What a crawler reads. Null for a manual item. */
    sourceUrl: string | null;
    /** Where the item is in our pipeline. */
    status: LibraryItemStatus;
    /** Everything type-specific. Which shape it is follows from `type`: a novel returns NovelMetadataDto, an image ImageSetMetadataDto, a video VideoSetMetadataDto. */
    metadata: NovelMetadataDto;
    /** Rewritten on every write. The listing is ordered by it. */
    updatedAt: string;
}

export interface LibraryItemPageDto {
    /** This page, ordered by `updatedAt` descending. */
    items: LibraryListItemDto[];
    /** How many items match the filter — not how many this page holds. */
    total: number;
    /** 1-based. */
    page: number;
    pageSize: number;
}

export interface LibraryItemDto {
    id: string;
    /** Set on creation and immutable after it. */
    type: LibraryItemType;
    title: string;
    /** A cover image URL, or null where the listing draws its placeholder. */
    coverUrl: string | null;
    /** Set on creation and immutable after it. */
    sourceMode: LibrarySourceMode;
    /** `Manual`, or the crawler's name. */
    sourceName: string;
    /** What a crawler reads. Null for a manual item. */
    sourceUrl: string | null;
    /** Where the item is in our pipeline. */
    status: LibraryItemStatus;
    /** Everything type-specific. Which shape it is follows from `type`: a novel returns NovelMetadataDto, an image ImageSetMetadataDto, a video VideoSetMetadataDto. */
    metadata: NovelMetadataDto;
    createdAt: string;
    /** Rewritten on every write. The listing is ordered by it. */
    updatedAt: string;
}

export interface LibraryItemMetadataDto {
    /** The work's own status, not the item's pipeline status. */
    status?: NovelStatus;
    author?: string;
    language?: string;
    genres?: string[];
    description?: string;
}

export interface CreateLibraryItemDto {
    /** Immutable after creation — it decides the shape of `metadata`. */
    type: LibraryItemType;
    title: string;
    /** A link to a cover image. Null, or left out, for the placeholder. */
    coverUrl?: string | null;
    /** Immutable after creation — it decides how content arrives. */
    sourceMode: LibrarySourceMode;
    /** Which crawler, for a crawler item — required of one. A manual item is `Manual`, whatever is sent. */
    sourceName?: string;
    /** What the crawler reads. Required of a crawler item, and refused of a manual one. */
    sourceUrl?: string | null;
    /** A novel item only. An image or video item has nothing writable here. */
    metadata?: LibraryItemMetadataDto;
}

/** Defaults to `draft` when left out, like every other omitted field. */
export type WritableLibraryItemStatus = "draft" | "ready";

export interface UpdateLibraryItemDto {
    /** Immutable after creation — it decides the shape of `metadata`. */
    type: LibraryItemType;
    title: string;
    /** A link to a cover image. Null, or left out, for the placeholder. */
    coverUrl?: string | null;
    /** Immutable after creation — it decides how content arrives. */
    sourceMode: LibrarySourceMode;
    /** Which crawler, for a crawler item — required of one. A manual item is `Manual`, whatever is sent. */
    sourceName?: string;
    /** What the crawler reads. Required of a crawler item, and refused of a manual one. */
    sourceUrl?: string | null;
    /** A novel item only. An image or video item has nothing writable here. */
    metadata?: LibraryItemMetadataDto;
    /** Defaults to `draft` when left out, like every other omitted field. */
    status?: WritableLibraryItemStatus;
}

export interface LibraryContentPageDto {
    /** Chapters by their number, assets by their name. */
    items: NovelChapterDto[];
    /** What matches the filter, not what this page holds. */
    total: number;
    page: number;
    pageSize: number;
}

export interface CreateLibraryContentDto {
    /** A chapter only. Defaults to the next number up. */
    index?: number;
    /** A chapter only, and required of one. */
    title?: string;
    /** A chapter only. */
    language?: string;
    /** A chapter only. Counted by whoever wrote the text — see the known limits. */
    words?: number;
    /** An image or video asset only, and required of one. */
    filename?: string;
    /** An image or video asset only. Bytes, as the uploader reports them. */
    filesize?: number;
    /** Where the browser put the bytes. Left out for a placeholder row. */
    contentUrl?: string | null;
}

export interface UpdateLibraryContentDto {
    /** A chapter only. Defaults to the next number up. */
    index?: number;
    /** A chapter only, and required of one. */
    title?: string;
    /** A chapter only. */
    language?: string;
    /** A chapter only. Counted by whoever wrote the text — see the known limits. */
    words?: number;
    /** An image or video asset only, and required of one. */
    filename?: string;
    /** An image or video asset only. Bytes, as the uploader reports them. */
    filesize?: number;
    /** Where the browser put the bytes. Left out for a placeholder row. */
    contentUrl?: string | null;
}

export interface ValidateDto {
    /** One of the registered crawlers. A name that is not registered is a 404. */
    crawler: string;
    /** The book's URL on the source site. A URL on another site is a 400. */
    sourceUrl: string;
}

export interface NovelPreviewMetadataDto {
    /** The canonical book URL, so two spellings of one book normalise to one. */
    sourceUrl: string;
    title: string;
    author: string;
    /** The work's own status, mapped from the source's word for it. */
    status: NovelStatus;
    /** From the crawler's entry — the source does not publish one. */
    language: string;
    /** The source category, where it has one. */
    genres: string[];
    description: string;
    /** The newest chapter, as the source names it. */
    latest: string;
    latestUrl: string;
    /** When the source last changed, in the source's own format. Not an ISO instant, and not compared to one. */
    updatedAt: string;
    /** Where the cover lives on the source. Behind the same protection as the site, so not for an `<img>` — use `coverBinary`. */
    coverUrl: string | null;
}

export interface PreviewChapterDto {
    /** Reading order, from 1. */
    index: number;
    title: string;
    url: string;
}

export interface NovelPreviewDto {
    metadata: NovelPreviewMetadataDto;
    /** Every chapter, in reading order. The preview draws a count from it; the job runner will draw content. */
    chapters: PreviewChapterDto[];
    /** The cover as a data URI — the bytes and their type in one string. Null where the book has no cover, or fetching it failed. */
    coverBinary: string | null;
}

export interface PreviewDto {
    /** The crawler's kind, which decides the shape of `content`. */
    type: LibraryItemType;
    content: NovelPreviewDto;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    throw new ApiException(message, status, response, headers, result);
}